stages:
  - build

build:
    image: docker:20.10.10
    services:
        - docker:20.10.10-dind
    only:
        - tags
    script:
        - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
        - docker build -f $DOCKERFILE -t "$CI_REGISTRY_IMAGE/$IMAGE:latest" -t "$CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_TAG" .
        - docker push "$CI_REGISTRY_IMAGE/$IMAGE:latest"
        - docker push "$CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_TAG"
    parallel:
      matrix:
        - DOCKERFILE: docker/megaphone-be.dockerfile
          IMAGE: megaphone
        - DOCKERFILE: docker/megaphone-chat.dockerfile
          IMAGE: megaphone-chat-svc
        - DOCKERFILE: docker/megaphone-chat-fe.dockerfile
          IMAGE: megaphone-chat-app
        