apiVersion: d71.dev/v1
kind: Megaphone
metadata:
  name: megaphone-demo
  namespace: default
spec:
  replicas: 2
  image: dghila/megaphone:0.6.0
  virtualAgentsPerNode: 3
  resources:
    limits:
      cpu: 20m
      memory: 50Mi
    requests:
      cpu: 20m
      memory: 50Mi
