apiVersion: d71.dev/v1
kind: Megaphone
metadata:
  name: megaphone-demo
  namespace: default
spec:
  replicas: 2
  image: dghila/megaphone:0.8.9
  virtualAgentsPerNode: 3
  resources:
    limits:
      cpu: 50m
      memory: 150Mi
    requests:
      cpu: 20m
      memory: 50Mi
